# 開発環境用のdocker-compose
version: '3.2'

services:

  database:
    restart: always
    image: mysql:5.7
    ports:
      - 4306:3306
    volumes:
      - mysql-datavolume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  app:
    build:
      context: .
      dockerfile: ./docker/development/Dockerfile
    command: >
      bash -c "
        rm -f tmp/pids/server.pid &&
        bundle install --quiet &&
        bundle exec rails db:migrate:reset &&
        bundle exec rails s -p 3000 -b '0.0.0.0'
      "
    ports:
      - "3000:3000"
    volumes:
      - .:/hello_world_rails
      - "bundle:/usr/local/bundle"
    depends_on:
      - database
    tty: true
    stdin_open: true

volumes:
  bundle:
    driver: local
  mysql-datavolume:
    driver: local
