---
- name: register repo for Nginx
  yum:
    name: http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
    state: installed
  become: yes

- name: ensure nginx/conf.d is empty
  shell: rm -f /etc/nginx/conf.d/*
  become: yes

- name: Install nginx
  yum:
    name: nginx
    state: latest
  become: yes

- name: Configure Nginx
  become: yes
  template:
    src: nginx.conf.j2
    dest: "/etc/nginx/nginx.conf"
  notify:
      - reload nginx

- name: set auto start
  sudo: true
  shell: chkconfig nginx on

# - name: Make directory for SSL keys
#   sudo: yes
#   command: mkdir -p /etc/nginx/ssl

# - name: set SSL keys
#   sudo: yes
#   copy:
#     src: secret/nginx.key
#     dest: /etc/nginx/ssl/nginx.key
#   when: nginx.upload_ssl_keys

# - name: set SSL cert
#   sudo: yes
#   copy:
#     src: secret/nginx.crt
#     dest: /etc/nginx/ssl/nginx.crt
#   when: nginx.upload_ssl_keys

# - name: Generate SSL
#   sudo: yes
#   command: openssl req -x509 -nodes -subj "/C=JP/ST=Kanagawa/L=Yokohama/O=Example Inc./CN={{ rails.yml.application }}" -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/{{ rails.yml.application }}.key -out /etc/nginx/ssl/{{ rails.yml.application }}.crt
#   when: not nginx.upload_ssl_keys

# - name: run up services
#   include: service.yml
